[package]
name = "snowc-tree-walker"
version = "0.0.0"
edition = "2021"

[dependencies]
snowc-parse = { path = "../snowc-parse" }
annotate-snippets = { version = "0.9.1", features = ["color"] }
thiserror = "1.0.40"
anyhow = "1.0.71"

[dev-dependencies]
pretty_assertions = "1.3.0"
