[package]
name = "snowc"
version = "0.0.0"
edition = "2021"

[dependencies]
snowc-parse = { path="./crates/snowc-parse" }
snowc-error-messages = { path="./crates/snowc-error-messages" }
snowc-repl = { path="./crates/snowc-repl" }
snowc-tree-walker-eval = { path="./crates/snowc-tree-walker-eval" }
snowc-type-checker = { path="./crates/snowc-type-checker" }
snowc-errors = { path="./crates/snowc-errors" }
clap = { version = "4.0.29", features = ["cargo"] }

[workspace]
members = [
    "./crates/*",
]

[[bin]]
name = "main"
path = "src/main.rs"

[lib]
name = "snowc"
path = "src/lib.rs"

[profile.release]
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary*

