[package]
name = "snowc"
version = "0.0.0"
edition = "2021"

[dependencies]
snowc-parse = { path="./crates/snowc-parse" }
snowc-error-messages = { path="./crates/snowc-error-messages" }
snowc-repl = { path="./crates/snowc-repl" }

[dev-dependencies]
pretty_assertions = "1.1.0"

[workspace]
members = [
    "./crates/*",
]
