[package]
name = "snowc"
version = "0.0.0"
edition = "2021"

[dependencies]
# env_logger = "0.9.0"
# rustyline = "9.0.0"
# rustyline-derive = "0.5.0"
clap = { version = "3.1.18", features = ["cargo"] }


[dev-dependencies]
pretty_assertions = "1.1.0"
