[package]
name = "snowc-lexer"
version = "0.0.0"
edition = "2021"

[dependencies]
insta = { version = "1.34.0", features = ["yaml"] }

[dev-dependencies]
pretty_assertions = "1.3.0"
insta = { version = "1.29.0", features = ["yaml"] }
