[package]
name = "snow-vm"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["cargo"] }

[[bin]]
name = "machine"
path = "src/main.rs"

[lib]
name = "vm"
path = "src/lib.rs"
