[package]
name = "swrt"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["cargo"] }
rustyline = "10.0.0"

[[bin]]
name = "swrt"
path = "src/main.rs"

[lib]
name = "vm"
path = "src/lib.rs"
