[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
scanner = { path = "../scanner" }
snowc-errors = {path = "../snowc-errors" }

[dev-dependencies]
pretty_assertions = '1.1.0'
