[package]
name = "snowc-parse"
version = "0.1.0"
edition = "2021"

[dependencies]
snowc-lexer = { path = "../snowc-lexer" }
snowc-errors = {path = "../snowc-errors" }

[dev-dependencies]
pretty_assertions = '1.1.0'
