use super::parse::TokenOp;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OpCode {
    Load,
    LoadM,
    Push,
    Pop,
    Aloc,
    Setm,
    Add,
    Sub,
    Div,
    Mod,
    Mul,
    Jmp,
    Jeq,
    Jne,
    Eq,
    Neq,
    Gt,
    Geq,
    Lt,
    Leq,
    Inc,
    Dec,
    Call,
    Ret,
    Prts,
    Prti,
    Hlt,
    Nop,
    Ige,
}

impl From<&TokenOp> for OpCode {
    fn from(value: &TokenOp) -> Self {
        match value {
            TokenOp::Load(..) => Self::Load,
            TokenOp::Push(..) => Self::Push,
            TokenOp::Pop(..) => Self::Pop,
            TokenOp::Aloc(..) => Self::Aloc,
            TokenOp::LoadM(..) => Self::LoadM,
            TokenOp::Setm(..) => Self::Setm,
            TokenOp::Add(..) => Self::Add,
            TokenOp::Sub(..) => Self::Sub,
            TokenOp::Div(..) => Self::Div,
            TokenOp::Mod(..) => Self::Mod,
            TokenOp::Mul(..) => Self::Mul,
            TokenOp::Jmp(..) => Self::Jmp,
            TokenOp::Jeq(..) => Self::Jeq,
            TokenOp::Jne(..) => Self::Jne,
            TokenOp::Neq(..) => Self::Neq,
            TokenOp::Inc(..) => Self::Inc,
            TokenOp::Dec(..) => Self::Dec,
            TokenOp::Eq(..) => Self::Eq,
            TokenOp::Gt(..) => Self::Gt,
            TokenOp::Geq(..) => Self::Geq,
            TokenOp::Lt(..) => Self::Lt,
            TokenOp::Leq(..) => Self::Leq,
            TokenOp::Call(..) => Self::Call,
            TokenOp::Prts(..) => Self::Prts,
            TokenOp::Prti(..) => Self::Prti,
            TokenOp::Ret => Self::Ret,
            TokenOp::Hlt => Self::Hlt,
            TokenOp::Nop => Self::Nop,
        }
    }
}
impl From<u8> for OpCode {
    fn from(value: u8) -> Self {
        match value {
            0 => Self::Load,
            1 => Self::LoadM,
            2 => Self::Push,
            3 => Self::Pop,
            4 => Self::Aloc,
            5 => Self::Setm,
            6 => Self::Add,
            7 => Self::Sub,
            8 => Self::Div,
            9 => Self::Mod,
            10 => Self::Mul,
            11 => Self::Jmp,
            12 => Self::Jeq,
            13 => Self::Jne,
            14 => Self::Eq,
            15 => Self::Neq,
            16 => Self::Gt,
            17 => Self::Geq,
            18 => Self::Lt,
            19 => Self::Leq,
            20 => Self::Inc,
            21 => Self::Dec,
            22 => Self::Call,
            23 => Self::Ret,
            24 => Self::Prts,
            25 => Self::Prti,
            26 => Self::Hlt,
            27 => Self::Nop,
            _ => Self::Ige,
        }
    }
}
